# Generated by Django 6.0.2 on 2026-02-27 02:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_add_program_model'),
        ('stock', '0003_alter_transaction_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, help_text='Leave blank to auto-generate (e.g., REC-YYYYMM-XXXXX)', max_length=100, unique=True)),
                ('recall_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('COMPLETED', 'Selesai')], default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recalls', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='items.supplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_recalls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recalls',
                'ordering': ['-recall_date'],
            },
        ),
        migrations.CreateModel(
            name='RecallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Alasan recall')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_items', to='items.item')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recall.recall')),
                ('stock', models.ForeignKey(help_text='Specific batch being recalled', on_delete=django.db.models.deletion.PROTECT, related_name='recall_items', to='stock.stock')),
            ],
            options={
                'db_table': 'recall_items',
            },
        ),
    ]
