# Generated by Django 6.0.2 on 2026-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('RECEIVING', 'Penerimaan'), ('DISTRIBUTION', 'Distribusi'), ('ADJUSTMENT', 'Penyesuaian'), ('INITIAL_IMPORT', 'Import Awal'), ('RECALL', 'Recall'), ('EXPIRED', 'Kedaluwarsa')], max_length=20),
        ),
    ]
