# Generated by Django 6.0.2 on 2026-03-11 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_program_model'),
        ('stock', '0003_alter_transaction_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('RECEIVING', 'Penerimaan'), ('DISTRIBUTION', 'Distribusi'), ('ADJUSTMENT', 'Penyesuaian'), ('INITIAL_IMPORT', 'Import Awal'), ('RECALL', 'Recall'), ('EXPIRED', 'Kedaluwarsa'), ('TRANSFER', 'Mutasi Lokasi')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Selesai')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_to', to='items.location')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_from', to='items.location')),
            ],
            options={
                'db_table': 'stock_transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_items', to='items.item')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='stock.stock')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stocktransfer')),
            ],
            options={
                'db_table': 'stock_transfer_items',
                'ordering': ['id'],
            },
        ),
    ]
