# Generated by Django 6.0.2 on 2026-03-05 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_program_model'),
        ('receiving', '0003_receiving_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiving',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_receivings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiving',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiving',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_receivings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiving',
            name='closed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receiving',
            name='is_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_items', to='items.location'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('PARTIAL', 'Diterima Sebagian'), ('RECEIVED', 'Diterima Lengkap'), ('CLOSED', 'Ditutup'), ('VERIFIED', 'Terverifikasi')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ReceivingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_order_items', to='items.item')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='receiving.receiving')),
            ],
            options={
                'db_table': 'receiving_order_items',
            },
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='receiving.receivingorderitem'),
        ),
    ]
