# Generated by Django 6.0.2 on 2026-03-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0003_alter_transaction_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, help_text='Kosongkan untuk auto-generate (SO-YYYYMM-XXXXX)', max_length=100, unique=True)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Bulanan'), ('QUARTERLY', 'Triwulan'), ('SEMESTER', 'Semester'), ('YEARLY', 'Tahunan')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'Sedang Berjalan'), ('COMPLETED', 'Selesai')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_opnames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_opnames',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOpnameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='Snapshot of stock quantity at time of opname creation', max_digits=12)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Actual counted quantity by staff', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Catatan jika ada selisih')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opname_items', to='stock.stock')),
                ('stock_opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_opname.stockopname')),
            ],
            options={
                'db_table': 'stock_opname_items',
                'ordering': ['stock__item__nama_barang', 'stock__location__code'],
                'unique_together': {('stock_opname', 'stock')},
            },
        ),
    ]
