# Generated by Django 6.0.2 on 2026-02-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_category_is_controlled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kode_barang',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
