# Generated by Django 6.0.2 on 2026-02-26 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_kode_barang_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='program_name',
        ),
        migrations.AddField(
            model_name='item',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Health program (TB, HIV, Malaria, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.program'),
        ),
    ]
